version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: GitLearningProjectWithSpringAndReact
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .

    container_name: first-docker-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/GitLearningProjectWithSpringAndReact
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"

  frontend:
    build:
      context: "C:/Users/User/Desktop/Job and study/Job/GitProjectWithReactAndSpring/my-react-app"
      dockerfile: Dockerfile
    container_name: first-docker-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pg_data:
